### ISSUE TITLE
debins-gtk'in URL'sine ulaşılamıyor

### ISSUE THREAD

**Issue by Afacanc38** [eminfedar/eminfedar#1]
debins-gtk'in URL'sini yanlış girmişsiniz hocam.

![Ekran görüntüsü 2021-03-24 19-37-23](https://user-images.githubusercontent.com/66299502/112347951-64638380-8cd8-11eb-92b7-66752c5a6222.png)

**Comment by eminfedar** [comment]
kod.pardus.org.tr'de geçici bir sorun var sanırım, açılınca düzelecektir.

Edit: gov.tr yazmışım düzelteyim teşekkürler :)
